# -*- coding: utf-8 -*-
"""chat bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IXP-z58JElSXfn__ubItA5qFPx5XYBd
"""

from nltk.chat.util import Chat, reflections

pairs =[
    # Removed extra nesting here
    ["my name is (.*)",['hi %1']],
    ['(hi|hello|hey|hola )',['Namaste','hi','hello','hay thare']],
    ['my neme is (.*) and my age is(.*)',['your neme is %1 and your age is %2']]
]

chat=Chat(pairs,reflections )
chat.converse()